/* ============================================================
   99_cleanup.sql — Drop everything created by this project
   ============================================================ */

DROP PIPE IF EXISTS FINOPS_LAB.RAW.COST_PIPE;

DROP TABLE IF EXISTS FINOPS_LAB.CURATED.FACT_COST_DAILY;
DROP TABLE IF EXISTS FINOPS_LAB.CURATED.DIM_ACCOUNT;
DROP TABLE IF EXISTS FINOPS_LAB.CURATED.DIM_SERVICE;
DROP TABLE IF EXISTS FINOPS_LAB.CURATED.DIM_TAGS;

DROP TABLE IF EXISTS FINOPS_LAB.RAW.COST_RAW;
DROP VIEW  IF EXISTS FINOPS_LAB.RAW.COST_SYNTH_JSON_V;
DROP TABLE IF EXISTS FINOPS_LAB.RAW.COST_SYNTH_SRC;

DROP STAGE       IF EXISTS FINOPS_LAB.RAW.COST_STAGE;
DROP FILE FORMAT IF EXISTS FINOPS_LAB.RAW.JSON_FF;

DROP TABLE IF EXISTS FINOPS_LAB.RAW.PIPELINE_STATE;

DROP SCHEMA IF EXISTS FINOPS_LAB.CURATED;
DROP SCHEMA IF EXISTS FINOPS_LAB.RAW;

DROP DATABASE IF EXISTS FINOPS_LAB;

DROP WAREHOUSE IF EXISTS FINOPS_WH;
